import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const data = await fetch('https://jsonplaceholder.typicode.com/posts')
  console.log(data);
  const posts = await data.json();

  return {
    props : {
      posts
    }
  }
}

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {posts.map(post => (
          <Link href={`/article/${post.id}`} key={post.id}><a>{post.title}</a></Link>
      ))}
    </div>
  )
}
